apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-live
#  specification
spec:
#  副本数量
#  作业
#  replicas: 2
  replicas: 3
  selector:
    matchLabels:
      app: webook-live
#      template 描述的是你的 POD 是什么样的
  template:
    metadata:
      labels:
        app: webook-live
#    POD 的具体信息
    spec:
      containers:
        - name: webook
          image: flycash/webook-live:v0.0.1
          ports:
#            - 作业
#            - containerPort: 8081
            - containerPort: 8080
